# server/app/etl/vendor_mappings.py
AGENT_MAPPINGS = [
  {"vendor_code":"CONCENTRIX","vendor_name":"Concentrix","sheets":["CON Master List"],"headers":["Employee ID","Full Legal Name","HP ID"],"map":{"employee_id":["Employee ID"],"full_name":["Full Legal Name"],"email":["Email"],"role_title":["Job Title"],"lob":["Queue"],"supervisor_name":["Team Leader"],"wave":["Wave"],"start_date":["Start Date"],"production_start_date":["Prod Date"],"status":["Status"],"hp_id":["HP ID"],"password":["Password"]}},
  {"vendor_code":"TP","vendor_name":"Teleperformance","sheets":["Zendesk"],"headers":["Name","Email","TP Emp ID"],"map":{"employee_id":["TP Emp ID"],"full_name":["Name"],"email":["Email"],"status":["Status"],"password":["Password"]}},
  {"vendor_code":"WNS","vendor_name":"WNS","sheets":["Active agents"],"headers":["First Name","Last Name","ID*"],"map":{"first_name":["First Name"],"last_name":["Last Name"],"email":["Email"],"employee_id":["ID*"],"role_title":["Task / Position","Position"],"supervisor_name":["Supervisor"],"wave":["Wave","Wave "],"start_date":["Start Date"],"production_start_date":["Production Start Date"],"billable":["Billable Hour Yes/No"],"admin_access":["Admin Access"],"password":["HP Password*","Password*"]}},
  {"vendor_code":"BUWELO_COL","vendor_name":"Buwelo Colombia","sheets":["Active Agents - COL"],"headers":["First Name","Last Name","ID*"],"map":{"first_name":["First Name"],"last_name":["Last Name"],"email":["Email"],"employee_id":["ID*"],"role_title":["Position /LOB","Position"],"supervisor_name":["Supervisor"],"wave":["Wave","Wave "],"start_date":["Start Date"],"production_start_date":["Production Start Date"],"billable":["Billable Hour Yes/No"],"admin_access":["Admin Access"],"password":["Password*"]}},
  {"vendor_code":"BUWELO_GH","vendor_name":"Buwelo Ghana","sheets":["Active Agents - GH"],"headers":["First Name","Last Name","ID*"],"map":{"first_name":["First Name"],"last_name":["Last Name"],"email":["Email"],"employee_id":["ID*"],"role_title":["Position /LOB","Position"],"supervisor_name":["Supervisor"],"wave":["Wave","Wave "],"start_date":["Start Date"],"production_start_date":["Production Start Date"],"billable":["Billable Hour Yes/No"],"admin_access":["Admin Access"],"password":["Password*"]}},
  {"vendor_code":"BUWELO_PH","vendor_name":"Buwelo Philippines","sheets":["Active Agents - PH"],"headers":["First Name","Last Name","ID*"],"map":{"first_name":["First Name"],"last_name":["Last Name"],"email":["Email"],"employee_id":["ID*"],"role_title":["Position"],"supervisor_name":["Supervisor"],"wave":["Wave","Wave "],"start_date":["Start Date"],"billable":["Billable Hour Yes/No"],"admin_access":["Admin Access"],"password":["Password*"]}}
]
